import { Router } from "express";
import { authenticateJWT, authorizeRoles } from "../../../shared/presentation/middlewares/auth.js";
import { UserRepositoryPg } from "../infrastructure/user.repository.js";
import { UserService } from "../application/user.service.js";
import { UserController } from "./user.controller.js";
const repo = new UserRepositoryPg();
const service = new UserService(repo);
const controller = new UserController(service);
export const userRouter = Router();
userRouter.get("/", authenticateJWT, authorizeRoles("ADMIN"), controller.getAll);
userRouter.get("/:id", authenticateJWT, authorizeRoles("ADMIN"), controller.getById);
userRouter.put("/:id", authenticateJWT, authorizeRoles("ADMIN"), controller.update);
userRouter.delete("/:id", authenticateJWT, authorizeRoles("ADMIN"), controller.delete);
