import { Router } from "express";
import { UserRepositoryPg } from "../infrastructure/user.repository.js";
import { UserService } from "../application/user.service.js";
import { UserController } from "./user.controller.js";
const repo = new UserRepositoryPg();
const service = new UserService(repo);
const controller = new UserController(service);
export const userRouter = Router();
userRouter.get("/", controller.getAll);
userRouter.get("/:id", controller.getById);
userRouter.put("/:id", controller.update);
userRouter.delete("/:id", controller.delete);
