import { Router } from "express";
import { OrderRepositoryPg } from "../infrastructure/order.repository.js";
import { OrderService } from "../application/order.service.js";
import { OrderController } from "./order.controller.js";
const repo = new OrderRepositoryPg();
const service = new OrderService(repo);
const controller = new OrderController(service);
export const orderRouter = Router();
orderRouter.post("/", controller.checkout);
orderRouter.get("/", controller.getAll);
orderRouter.get("/:id", controller.getById);
orderRouter.post("/cancel/:id", controller.cancel);
