import { Router } from "express";
import { authenticateJWT } from "../../../shared/presentation/middlewares/auth.js";
import { OrderRepositoryPg } from "../infrastructure/order.repository.js";
import { OrderService } from "../application/order.service.js";
import { OrderController } from "./order.controller.js";
const repo = new OrderRepositoryPg();
const service = new OrderService(repo);
const controller = new OrderController(service);
export const orderRouter = Router();
orderRouter.post("/", authenticateJWT, controller.checkout);
orderRouter.get("/", authenticateJWT, controller.getAll);
orderRouter.get("/:id", authenticateJWT, controller.getById);
orderRouter.post("/cancel/:id", authenticateJWT, controller.cancel);
