import { Router } from "express";
import { authorizeRoles } from "../../../shared/presentation/middlewares/auth.js";
import { CustomerRepositoryPg } from "../infrastructure/customer.repository.js";
import { CustomerService } from "../application/customer.service.js";
import { CustomerController } from "./customer.controller.js";
const repo = new CustomerRepositoryPg();
const service = new CustomerService(repo);
const controller = new CustomerController(service);
export const customerRouter = Router();
customerRouter.post("/", controller.create);
customerRouter.get("/", controller.getAll);
customerRouter.get("/phone/:phone", controller.getByPhone);
customerRouter.put("/points/:id", authorizeRoles("ADMIN"), controller.addPoints);
customerRouter.delete("/:id", authorizeRoles("ADMIN"), controller.delete);
