import { Router } from "express";
import { authenticateJWT, authorizeRoles } from "../../../shared/presentation/middlewares/auth.js";
import { CategoryRepositoryPg } from "../infrastructure/category.repository.js";
import { CategoryService } from "../application/category.service.js";
import { CategoryController } from "./category.controller.js";
const repo = new CategoryRepositoryPg();
const service = new CategoryService(repo);
const controller = new CategoryController(service);
export const categoryRouter = Router();
categoryRouter.get("/", controller.getAll);
categoryRouter.get("/:id", controller.getOne);
categoryRouter.post("/", authenticateJWT, authorizeRoles("ADMIN"), controller.create);
categoryRouter.put("/:id", authenticateJWT, authorizeRoles("ADMIN"), controller.update);
categoryRouter.delete("/:id", authenticateJWT, authorizeRoles("ADMIN"), controller.delete);
